# Generated by Django 3.2 on 2021-04-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('cod', models.TextField(db_column='cod', primary_key=True, serialize=False)),
                ('des', models.TextField(db_column='des')),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Postagens',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('frequencia', models.CharField(max_length=100)),
                ('tit_proprio', models.CharField(max_length=100)),
                ('titulo_abreviado', models.CharField(max_length=100)),
                ('cod_ccn', models.CharField(max_length=100)),
                ('cod_issn', models.CharField(max_length=100)),
                ('cod_issn_online', models.CharField(max_length=100)),
                ('home_page', models.CharField(max_length=100)),
                ('situacao', models.CharField(max_length=100)),
                ('designacoes', models.CharField(max_length=100)),
                ('imprentas', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=100)),
                ('assunto', models.CharField(max_length=100)),
                ('titulo_adicional', models.CharField(max_length=100)),
                ('titulo_completo',models.CharField(max_length=100)),
            ],
        ),
    ]
