# Generated by Django 3.2 on 2021-04-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
