# Generated by Django 3.2.6 on 2021-09-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccn', '0002_delete_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagens_titulo',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_completo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Universidades',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('publ_cod', models.CharField(max_length=100)),
                ('bibl_cod', models.CharField(max_length=100)),
                ('conteudo', models.CharField(max_length=500)),
                ('uf_cod', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='postagens',
            name='imprentas',
            field=models.TextField(max_length=100),
        ),
    ]
