# Generated by Django 3.2.6 on 2022-01-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccn', '0003_auto_20210917_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('publ_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('seq', models.IntegerField()),
                ('titulo_completo', models.TextField()),
            ],
            options={
                'db_table': 'publicacao_titulo',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='postagens',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='postagens',
            name='designacoes',
        ),
        migrations.RemoveField(
            model_name='postagens',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='postagens',
            name='imprentas',
        ),
        migrations.RemoveField(
            model_name='postagens',
            name='titulo_adicional',
        ),
        migrations.AlterModelTable(
            name='postagens',
            table='ccn.publicacao',
        ),
    ]
