# Generated by Django 3.2.6 on 2022-01-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccn', '0004_auto_20220111_2052'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='titulos',
            table='ccn.publicacao_titulo',
        ),
    ]
